<a href="https://colab.research.google.com/github/anushkamundhe/SPAT/blob/anushka/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
# An array
arr = np.array([[1,2,3]])

In [8]:
arr

array([[1, 2, 3]])

In [9]:
# Dimensions and shape of an array

arr.ndim

2

In [10]:
a = np.array([[[]]])
a

array([], shape=(1, 1, 0), dtype=float64)

In [11]:
a.ndim
a.shape

(1, 1, 0)

In [12]:
# Create an array
np.arange(0,10,2)      # (start(included), stop(never included), steps)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(1,10,50)   # (start value(included), end value(never included), no. of values)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [14]:
np.logspace(1,3,3)    # logarithmic scale array ==> 10^1, 10^3,..., 3 points
          # (start, end, 3 -> 3 number of values)

array([  10.,  100., 1000.])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros([2,3,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [17]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [18]:
np.ones([4,2], dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [19]:
arr = np.full(4,2)    # an array full of any values
arr

array([2, 2, 2, 2])

In [20]:
arr = np.full([2,4], 6)    # [row, column], default
arr

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [21]:
arr = np.empty([2,3])    # uninitialized array -> create an array without setting any values
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.random.rand(11)       # generate random floats between 0 1o 1

array([0.35907383, 0.44941582, 0.33937786, 0.78325305, 0.72377426,
       0.31970158, 0.54700624, 0.30372896, 0.7847793 , 0.18507468,
       0.38268148])

In [23]:
np.random.randn()       # random floats from standard normal distrribution
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr = np.random.randint(1,10,15)    # random integers     # (start, end, no. of values or dimension size=(2,3)---> 2*3 we will get 6 values)
arr

array([7, 4, 1, 8, 1, 9, 2, 8, 6, 3, 8, 4, 8, 9, 7])

In [25]:
arr = np.random.randint(1,10,size = (2,3))
arr

array([[5, 5, 8],
       [1, 3, 5]])

DataTypes and Type Casting







In [26]:
arr = np.array([1,2,3.3,4])
print(type(arr))


<class 'numpy.ndarray'>


In [27]:
lst = [1,2,3,"hi",4.5]
print(type(lst))
arr = np.array(lst)          # conversion of list into array
arr

<class 'list'>


array(['1', '2', '3', 'hi', '4.5'], dtype='<U32')

In [28]:
arr = np.array([1,2,3.7j,4])
arr.dtype           # to check the type of the data  =========>  arr.dtype


dtype('complex128')

In [29]:
arr = np.array([1,2,3,4,5], dtype=float)        # to convert the datatype into another datatype
arr


array([1., 2., 3., 4., 5.])

In [30]:
# TypeCasting
# for converting array into another datatype we use ===> astype()

In [31]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [32]:
new_arr = arr.astype(float)
new_arr

array([1., 2., 3.])

In [33]:
# Typecasting errors :  we cannot convert the string into int or float or complex from an array

In [34]:
# Create multidimensional array

arr = np.array([[1,2,3],
               [4,5,6]])
arr
arr.ndim      # check dimension or size
arr.shape     # checks rows & columns
arr.size      # total elements / no. of values
arr.itemsize      # each element takes 8 bytes of memory

8

Array Reshaping ---> Reshape, Ravel, Flatten

In [35]:
# Reshape

arr = np.array([1,2,3,4,5,6])
arr
reshaped = arr.reshape(3,2)    # 3->rows & 2->columns
reshaped


array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# Ravel

# used to convert array into 1D array
# returns the view of the array

ravel = reshaped.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [37]:
ravel[0] = 20
print(ravel)
print(reshaped)

[20  2  3  4  5  6]
[[20  2]
 [ 3  4]
 [ 5  6]]


In [38]:
# Flatten

# it is also used to convert array into 1D array
# difference is ---> it returns the copy of the array

flat = reshaped.flatten()
flat
flat[0] = 1
print(reshaped)

[[20  2]
 [ 3  4]
 [ 5  6]]


In [39]:
# whenever we convert array into ravel() the changes are reflected in the original array
# and in flatten the changes are not reflected into array, the independent array is created

Arithmetic Operations on array


In [40]:
# creating two array

a = np.array([1,2,3])
b = np.array([4,5,6])
a
b


array([4, 5, 6])

In [41]:
from os import abort
# addition
print(a+b)  # or
c = np.add(a,b)


# subtraction
print(a-b)  # or
c = np.subtract(a,b)

# multiply
print(a*b)  # or
c = np.multiply(a,b)

# division
print(a/b)  # or
c = np.divide(a,b)

# modulus
print(b%a)  # or
c = np.mod(b,a)

# exponent
print(a**2)
print(b**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 1 0]
[1 4 9]
[16 25 36]


Universal Functions ---> ufuncs

In [42]:
arr = np.array([1,4,9,16,25])
arr
np.sqrt(arr)      # square root -> np.sqrt
np.exp([1,2])     # exponential -> np.exp -> e^x -> x is any number
np.sin(arr)      # sin -> np.sin
np.cos(arr)      # cos -> np.cos

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281])

Indexing and Slicing

In [43]:
arr = np.array([1,2,3,4,5])
arr[-4]    # indexing
arr[-1:-4:-2]   #slicing  ->  [start:end:step]
arr[::2]
arr[-3]

np.int64(3)

Multidimensional Slicing

In [44]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr.ndim

2

In [45]:
arr[0:2:]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [47]:
import numpy as np
# Iterator with nditer()
arr = np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
  print(x, end=" ")

1 2 3 4 5 6 

In [48]:
# ndenumerator -> both index + value  will generate
for ind,x in np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [49]:
# View

arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [51]:
view[0] = 20
view

array([20,  3])

In [52]:
arr

array([ 1, 20,  3,  4,  5])

In [55]:
# Copy

copy = arr[1:3].copy()
copy

array([20,  3])

In [57]:
copy[0] = 50
copy

array([50,  3])

In [58]:
arr

array([ 1, 20,  3,  4,  5])

Transpose of Matrix

In [63]:
arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr.transpose()      # transforming rows into columns and vice versa

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
# Swapaxes --> swap 2 specific axes in a matrix

arr = np.array([[[1,2,3],[4,5,6]]])
arr.shape

(1, 2, 3)

In [71]:
swap = np.swapaxes(arr,0,2)
swap.shape

(3, 2, 1)

In [77]:
# Concatenation
a = np.array([1,2])
b = np.array([3,4])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4])

In [79]:
# Vstack
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.vstack((arr1,arr2))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
# Hstack
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [83]:
np.stack((arr1,arr2), axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [85]:
arr1
np.split(arr1,2)

[array([[1, 2]]), array([[3, 4]])]

In [89]:
np.hsplit(arr1,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [87]:
np.vsplit(arr1,2)

[array([[1, 2]]), array([[3, 4]])]

In [91]:
# Repeating

arr = np.array([1,2,3,4])        # array is repeated twice
np.repeat(arr, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [93]:
# Tile

np.tile(arr,2)      # repeat whole array


array([1, 2, 3, 4, 1, 2, 3, 4])

Aggregate Functions   ---->   used to summarize the whole array

In [103]:
arr = np.array([1,2,3,4])


np.sum(arr)
np.mean(arr)
np.median(arr)
np.std(arr)
np.var(arr)
np.min(arr)
np.max(arr)
np.argmin(arr)
np.argmax(arr)


np.int64(3)

In [110]:
# Cumulative Operations  --->  it is used to calculate the running total


arr

array([1, 2, 3, 4])

In [111]:
np.cumsum(arr)

array([ 1,  3,  6, 10])

In [112]:
np.cumprod(arr)

array([ 1,  2,  6, 24])

Conditional based Choices

In [114]:
# Where

arr

array([1, 2, 3, 4])

In [116]:
np.where(arr>=2, 'high','low')

array(['low', 'high', 'high', 'high'], dtype='<U4')

In [120]:
arr = np.array([10,25,35,40])     # finds the value of the index where the condition meets
np.argwhere(arr>20)

array([[1],
       [2],
       [3]])

In [122]:
np.logical_and(arr>20, arr<40)

array([False,  True,  True, False])

In [124]:
np.logical_or(arr>20, arr<40)

array([ True,  True,  True,  True])

In [130]:
# Mask

mask = np.logical_and(arr>20, arr<40)
arr[mask]

array([25, 35])

In [131]:
mask

array([False,  True,  True, False])

In [138]:
# take
arr

array([10, 25, 35, 40])

In [135]:
np.take(arr, [0,2])   # fetch values at given index

array([10, 35])

In [139]:
np.nonzero(arr)

(array([0, 1, 2, 3]),)

Broadcasting

In [ ]:
# Broadcasting ---> stretching the smaller array to match the shape of the bigger array

# Numpy compare the shape of an array from the end (right to left)

# 1. If shapes are equal they are compatible
# 2. if one is 1, it can be stretched to match the other
# 3. If shapes are different and not 1 or equal --> error

In [144]:
arr = np.array([[1,2],[3,4]])

In [146]:
a = arr + 10
a

array([[11, 12],
       [13, 14]])

In [ ]:
# Vectorization

#np.vectorize()  --->  converta regular function to be applied on an array.

In [149]:
arr = np.array([4,3,2,1])

def square(x):
  return x*x

vfunc = np.vectorize(square)
vfunc(arr)

array([16,  9,  4,  1])

Dealing with missing Values

In [150]:
# np.nan  -->  not a number

a = np.array([1,2,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [161]:
# np.inf and -np.inf  --->   positive and negative infinites

In [ ]:
# np.isnan
# np.isinf
# np.isfinite

# These functions are used to detect any null values , infinite or finite values

In [157]:
np.isnan(a)

array([False, False,  True, False])

In [158]:
np.isinf(a)

array([False, False, False, False])

In [159]:
np.isfinite(a)

array([ True,  True, False,  True])

In [162]:
np.nan_to_num(a)      # null values get replaced by 0

array([1., 2., 0., 4.])